# Generated by Django 5.1 on 2024-09-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0003_remove_doctorregister_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregister',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctorregister',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='doctorregister',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='patientregister',
            name='profile_pic',
        ),
    ]
