# Generated by Django 5.1 on 2024-09-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0004_remove_doctorregister_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregister',
            name='years_of_experience',
        ),
    ]
