# Generated by Django 5.1 on 2024-09-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0005_remove_doctorregister_years_of_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregister',
            name='gender',
        ),
    ]
