# Generated by Django 5.1 on 2024-10-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0006_remove_doctorregister_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregister',
            name='gender',
        ),
    ]
