# Generated by Django 5.1 on 2024-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0008_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
